### PR TITLE
Add all necessary documentation for frontend components.

### PR DESCRIPTION
**Pull request by microcrit**
REWRITE HYPEEE!!!!!!!

### CODE REVIEW

**Comment by microcrit** [comment]
And yes I'm overdocumenting but yeah :)

**Comment by XOTlC** [comment]
depends, a lot of stuff is overdocumented

**Comment by XOTlC** [comment]
i would only document confusing stuff as well another note

**Comment by microcrit** [comment]
> depends, a lot of stuff is overdocumented

I've updated views so there is less documentation, and I will update the rest of the components to remove unnecessary comments as well.

**Comment by AWRATS** [comment]
shut up idc
________________________________

**Comment by zastlx** [comment]
so much overcoumentation, not need imo

**Comment by microcrit** [comment]
> so much overcoumentation, not need imo

I think we're all well aware as I'm asking for assistance from multiple people to help me reduce documentation

**Comment by microcrit** [comment]
@XOTlC @ItsSyfe im allowing maintainers to make edits please feel free to help me reduce documentation whenever

**Comment by microcrit** [comment]
closed due to inactivity

**Pull request closed without merging**
